add_newline    = false

[line_break]
disabled       = true

[character]
error_symbol   = '[󱎘](red)'
vimcmd_symbol  = '[](green)'
success_symbol = '[](green)'

[directory]
style = 'blue'
truncation_symbol = '.../'

[git_branch]
symbol = ' '

[lua]
symbol = ' '

[cmake]
symbol = ' '

[zig]
symbol = ' '
