# XDG
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"

# Zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# Go
export GOPATH="$HOME/.local/share/go"

# Rust
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"

# Bun
export BUN_INSTALL="$XDG_DATA_HOME/bun"

# Node
export NVM_DIR="$XDG_DATA_HOME/nvm"
export NPM_CONFIG_CACHE="$XDG_CACHE_HOME/npm"
export NPM_CONFIG_USERCONFIG="$NVM_DIR/.npmrc"
export NODE_REPL_HISTORY="$XDG_CACHE_HOME/node_repl_history"

# Default editor
export EDITOR=nvim
export VISUAL=nvim
export SUDO_EDITOR=nvim

# PATH
export PATH="$HOME/.local/bin:$GOPATH/bin:$BUN_INSTALL/bin:$XDG_DATA_HOME/src/zig:$CARGO_HOME/bin:$PATH"
